
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Menubar} from "@/components/Menubar";
import React from "react";
import {AnimatePresence} from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

 export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
 };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`inter.className bg-slate-900 min-h-screen`}>
    <div className="grid grid-cols-4 ">
        <div className="col-span-3"></div>
        <div className="col-span-1 z-50">
            <Menubar/>{/*gridの中に入れないと動かない*/}
        </div>
    </div>
    {children}
    </body>
    </html>
  );
}
